language: python
python:
  - "3.6"
install:
  - pip install progressbar2 requests invoke boto3 aws-requests-auth
cache: pip
script:
  - invoke poll-ci-build
git:
    depth: 3
deploy:
    provider: script
    script: bash ./scripts/build_deploy.sh
    on:
        tags: true
        condition: $TRAVIS_TAG =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
env:
    global:
        secure: kOrl0+i+Zb+FGcYld/C3Ir6Ag5ceOZ2IJLxkbOF04uw5O0GS3E0bNvb8KtTFj4dav34+Q+KCLbYkI5JLL460k+BBlV3qFFtLoMSukOmLeESgiDSRbekx/lEcg15gAt6eNhwHjkrLGXwCJDw/7nkoGVT8gmxx3gK+Ivt2ndAp3k3Gz7/qV9JFJr54XhPMNufDikGZboA/Vf5SsmaMf8HZXlQL/vYail5LTtcDCKs7u37oaUAouVRb/5C0ZEGa0/Its4UcLoTrdacwbAGwUmUSTX9nnMJOO9/q0ivXxLHSaydjuSEY3vKCSXupXzbiQpGpQ2pW6pM/Qur+xPJMuSJ70FXMbAdj3KX10Vub5cXt1CkawZMv4amzRl/+mhLl9l+z+OrTFBo9FgzM0cigguypGzwdFyohDMU38U/eWoFuoJL9uTvpXuA1pb49jLOi4DiCKUf53WFhLjZecvGw/RDaRqxSB/prucfGDDHd9nogn8kF1388AgbpHXkaIMKzfCBQfzEUK3CLX5qmxGjdiui2ITEeiRbmSzf5qqm7RxGAzjzVyprKMBWNUsAK2d5AGU/iVN/UD9PZY59MhUv8gJ8mnHJY2NVQ4AyuUkwv0REoNN1HR2U3PBA+YAl6DXc3d0QfEclCif6KORTZxsO4t6PteqFzD/RjDSxQLdFEhy/9hac=


